fixtures:
  repositories:
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
    cron_core:
      repo: "https://github.com/puppetlabs/puppetlabs-cron_core"
      puppet_version: '>= 6.0.0'
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    yumrepo_core:
      repo: "git://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      puppet_version: '>= 6.0.0'
  symlinks:
    curator: "#{source_dir}"
