source 'https://rubygems.org'

gem 'facter'
gem 'hiera'
gem 'metadata-json-lint'
gem 'parallel_tests', :require => false
gem 'pdk'
gem 'puppet', '~> 7.0'
gem 'puppet-blacksmith'
gem 'puppet-lint'
gem 'puppetlabs_spec_helper'
gem 'rake'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-puppet'
gem 'rspec-puppet-facts'
